package controllers

import (

	"challenge294/app/controllers/middlewares"

	"github.com/gin-gonic/gin"

	_ "challenge294/docs" // docs is generated by Swag CLI, you have to import it.

	ginSwagger "github.com/swaggo/gin-swagger"

	swaggerfiles "github.com/swaggo/files"
)

func StartApp(userControllers IUserControllers, productController IProductControllers) *gin.Engine {
	r := gin.Default()

	userRouter := r.Group("/users")
	{
		// UserRegister
		userRouter.POST("/register", userControllers.UserRegister)
		// UserLogin
		userRouter.POST("/login", userControllers.UserLogin)
	}

	productRouter := r.Group("/products")
	{
		productRouter.Use(middlewares.Authentication()) // Punya token yang valid ? lanjut : keluar

		// CreateProduct
		productRouter.POST("/", productController.CreateProduct) // Create, produk yang dibuat akan langsung diset dengan id user yang telah terautentikasi
		// ReadProduct
		productRouter.GET("/:productId", middlewares.ProductAuthorization(), productController.ReadProduct) // Read Product By ID
		// UpdateProduct
		productRouter.PUT("/:productId", middlewares.AdminOnlyAuthorization(), productController.UpdateProduct) // Update
		// DeleteProduct
		productRouter.DELETE("/:productId", middlewares.AdminOnlyAuthorization(), productController.DeleteProduct) // Delete
		// ReadAllProduct
		productRouter.GET("/", middlewares.AdminOnlyAuthorization(), productController.ReadAllProduct) // Read Product By ID
	}
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))

	return r
}